name 'codex-rangefinder'
description '5M-CodeX RangeFinder'
autor '5M-CodeX | TheStoicBear'
version '1.0.0'
fx_version 'cerulean'
game 'gta5'
lua54 'yes'
client_script 'client.lua'
shared_script 'config.lua'